name: E2E - iOS

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: macos-latest

    env:
      DEVELOPER_DIR: /Applications/Xcode_11.2.app

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1

      - name: Install lib dependencies
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false # Better for building libraries

      - name: Install app dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: ./example

      # - name: Setup debugging session
      #   uses: mxschmitt/action-tmate@v3

      # Cache Pod install at some point

      - name: Install pods
        run: pod install
        working-directory: ./example/ios

      - name: Install simulator utils
        run: |
          brew tap wix/brew
          brew install applesimutils

      - name: Build for detox
        run: yarn detox build --configuration ios.sim.release

      - name: Run tests
        run: yarn detox test --configuration ios.sim.release --cleanup
