name: Release

on:
  push:
    branches: [master]

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN_ADMIN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install app dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: ./example

      - name: Install lib dependencies
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false # Better for building libraries

      - name: Set Git credentials
        run: |
          git config user.email "aryella.lacerda@gmail.com"
          git config user.name "Aryella"

      - name: Prepend node path
        run: npm config set scripts-prepend-node-path auto

      - name: Generate version number, commit, tag, and Github release
        run: yarn release --ci

      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
