name: Unit | Component | Integration | Hook Testing

on:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    # A matrix allows you to create multiple jobs by performing variable substitution in a single job definition.
    # For example, you can use a matrix to create jobs for more than one supported version of a programming language, operating system, or tool.
    # A matrix reuses the job's configuration and creates a job for each matrix you configure.
    # strategy:
    #   matrix:
    #     node-version: [10.x, 12.x, 14.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install lib dependencies
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false # Better for building libraries

      - name: Check tests
        run: yarn test --coverage

      - name: Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Check linting
        run: yarn lint
